name: pgindent

on:
  push:
  pull_request:

jobs:
  pgindent:
    runs-on:
      - ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pg_version: [17]
    env:
      LLVM_VER: 18
      CPU: ${{ matrix.cpu }}
      CHECK_TYPE: pgindent
      COMPILER: gcc
    steps:
      - name: Checkout extension code into workspace directory
        uses: actions/checkout@v4
        with:
          path: vgram
      - name: Checkout PostgreSQL code into workspace directory
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: REL_${{ matrix.pg_version }}_STABLE
          path: postgresql
      - name: Setup prerequisites
        run: bash ./vgram/ci/prerequisites.sh
      - name: Build
        run: bash ./vgram/ci/build.sh
      - name: PGIndent
        run: bash ./vgram/ci/pgindent.sh
