name: static

on:
  push:
  pull_request:

jobs:
  static:
    runs-on:
      - ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pg_version: [13, 15, 17]
        compiler: [clang, gcc]
    env:
      LLVM_VER: 18
      CPU: ${{ matrix.cpu }}
      CHECK_TYPE: static
      COMPILER: ${{ matrix.compiler }}
    steps:
      - name: Checkout extension code into workspace directory
        uses: actions/checkout@v4
        with:
          path: vgram
      - name: Checkout PostgreSQL code into workspace directory
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: REL_${{ matrix.pg_version }}_STABLE
          path: postgresql
      - name: Setup prerequisites
        run: bash ./vgram/ci/prerequisites.sh
      - name: Build
        run: bash ./vgram/ci/build.sh
      - name: Static analysis
        run: bash ./vgram/ci/static.sh
